name: Publish NPM
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  publish-npm:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write  # Required for OIDC
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      # Ensure npm 11.5.1 or later is installed (for OIDC npm publishing)
      - name: Update npm
        run: npm install -g npm@latest
      - run: npm ci
      - name: Publish release to NPM
        if: github.event_name == 'release'
        run: npm publish
      - name: Publish @next to NPM
        if: github.event_name == 'workflow_dispatch'
        run: |
          node utils/update_canary_version.js
          npm publish --tag=next
